export const TIER_LIST_REQUEST = 'TIER_LIST_REQUEST';
export const TIER_LIST_SUCCESS = 'TIER_LIST_SUCCESS';
export const TIER_LIST_FAIL = 'TIER_LIST_FAIL';
export const TIER_PRODUCTS_REQUEST = 'TIER_PRODUCTS_REQUEST';
export const TIER_PRODUCTS_SUCCESS = 'TIER_PRODUCTS_SUCCESS';
export const TIER_PRODUCTS_FAIL = 'TIER_PRODUCTS_FAIL';
